Fixed workflow

diff --git a/.github/workflows/checkPullRequests.yaml b/.github/workflows/checkPullRequests.yaml
--- a/.github/workflows/checkPullRequests.yaml
+++ b/.github/workflows/checkPullRequests.yaml
@@ -8,9 +8,19 @@ on:
       - opened
 
 jobs:
-  specific_review_requested:
+  # dump:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: dump context
+  #       run: echo '${{ toJSON(github) }}'
+  review_requested:
     runs-on: ubuntu-latest
-    if: "(( github.event.pull_request.organization == 'exastro-suite') && ( github.event.pull_request.repository == 'exastro-it-automation-docs-dev'))"
+    if: "((github.repository == 'exastro-suite/exastro-it-automation-docs' \
+        && github.event.pull_request.head.repo.full_name == 'exastro-suite/exastro-it-automation-docs-dev') \
+      || (github.repository == 'exastro-suite/exastro-it-automation-docs-dev' \
+        && !startsWith(github.event.pull_request.head.repo.full_name, 'exastro-suite/')))"
     steps:
     - name: Check organization and repository
-      run: echo "::error::Disallowed Request source branch"
+      run: |
+        echo "::error::Disallowed Request source branch"
+        exit 1
